import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, BookOpen, Brain, CalendarDays, Check, CheckCircle2, ChevronRight, CircleHelp, Clock3, CloudRain, Heart, Home, Lightbulb, ListTodo, Menu, Moon, Play, Plus, Settings, Sparkles, Sun, Target, User, Wind, X} from 'lucide-react';
import './styles.css';

type Page='home'|'organizar'|'estudar'|'bemestar'|'perfil'|'diario'|'checkin'|'tarefas'|'habitos'|'pomodoro'|'foco'|'sons'|'respirar'|'progresso'|'calendario'|'ideias'|'privacidade'|'instituicao'|'ajuda';
const nav:[Page,string,any][]=[['home','Início',Home],['organizar','Organizar',ListTodo],['estudar','Estudar',BookOpen],['bemestar','Bem-estar',Heart],['perfil','Perfil',User]];
const moods=[['😄','Muito bem'],['🙂','Bem'],['😐','Neutro'],['😔','Não muito bem'],['😣','Difícil hoje']];
const messages=['Respirar também é produtividade.','Você não precisa fazer tudo hoje.','Pequenos passos também são progresso.','Seu descanso também faz parte da rotina.','Um momento de pausa pode mudar o restante do dia.'];
const initialTasks=[{id:1,name:'Estudar Banco de Dados',time:'09:00',priority:'Alta',done:false},{id:2,name:'Fazer trabalho de UX',time:'14:00',priority:'Média',done:true},{id:3,name:'Revisar apresentação',time:'18:30',priority:'Baixa',done:false}];
const initialHabits=[{id:1,name:'Beber água',icon:'💧',done:true},{id:2,name:'Estudar',icon:'📚',done:true},{id:3,name:'Caminhar',icon:'🏃',done:false},{id:4,name:'Pausa',icon:'🧘',done:false}];

function App(){
 const [page,setPage]=useState<Page>('home'); const [dark,setDark]=useState(localStorage.getItem('equilibra-theme')==='dark');
 const [mood,setMood]=useState(localStorage.getItem('equilibra-mood')||''); const [tasks,setTasks]=useState(()=>JSON.parse(localStorage.getItem('equilibra-tasks')||'null')||initialTasks); const [habits,setHabits]=useState(()=>JSON.parse(localStorage.getItem('equilibra-habits')||'null')||initialHabits); const [journal,setJournal]=useState<any[]>(()=>JSON.parse(localStorage.getItem('equilibra-journal')||'[]')); const [modal,setModal]=useState(false);
 useEffect(()=>{localStorage.setItem('equilibra-theme',dark?'dark':'light');document.documentElement.dataset.theme=dark?'dark':'light'},[dark]); useEffect(()=>localStorage.setItem('equilibra-tasks',JSON.stringify(tasks)),[tasks]); useEffect(()=>localStorage.setItem('equilibra-habits',JSON.stringify(habits)),[habits]); useEffect(()=>localStorage.setItem('equilibra-journal',JSON.stringify(journal)),[journal]);
 const title=useMemo(()=>({home:'Início',organizar:'Minha rotina',estudar:'Pronto para focar?',bemestar:'Cuide do seu ritmo',perfil:'Meu perfil',diario:'Meu diário',checkin:'Como você está se sentindo?',tarefas:'Minhas tarefas',habitos:'Meus hábitos',pomodoro:'Pomodoro',foco:'Modo foco',sons:'Sons ambientes',respirar:'Respire',progresso:'Meu progresso',calendario:'Calendário',ideias:'Caixa de ideias',privacidade:'Privacidade e segurança',instituicao:'Minha instituição',ajuda:'Preciso de ajuda'} as Record<Page,string>)[page],[page]);
 const go=(p:Page)=>{setPage(p);setModal(false)};
 return <div className="app"><header><div className="brand" onClick={()=>go('home')}><div className="brandMark"><Sparkles size={18}/></div><span>Equilibra</span></div><div className="headerActions"><button className="iconBtn" aria-label="Tema" onClick={()=>setDark(!dark)}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button><button className="avatar">L</button></div></header>
 <main><div className="pageHead"><div><span className="eyebrow">{page==='home'?'Seu espaço pessoal': 'Equilibra'}</span><h1>{title}</h1></div>{page!=='home'&&<button className="back" onClick={()=>go('home')}>Início</button>}</div>
 {page==='home'&&<HomePage mood={mood} setMood={m=>{setMood(m);localStorage.setItem('equilibra-mood',m)}} tasks={tasks} habits={habits} go={go}/>} 
 {page==='organizar'&&<Organize go={go} tasks={tasks} habits={habits}/>} {page==='estudar'&&<Study go={go}/>} {page==='bemestar'&&<Well go={go}/>} {page==='perfil'&&<Profile go={go} dark={dark} setDark={setDark}/>} 
 {page==='diario'&&<Journal journal={journal} setJournal={setJournal}/>} {page==='checkin'&&<Checkin mood={mood} setMood={setMood}/>} {page==='tarefas'&&<Tasks tasks={tasks} setTasks={setTasks}/>} {page==='habitos'&&<Habits habits={habits} setHabits={setHabits}/>} {page==='pomodoro'&&<Pomodoro/>} {page==='foco'&&<Focus/>} {page==='sons'&&<Sounds/>} {page==='respirar'&&<Breathing/>} {page==='progresso'&&<Progress/>} {page==='calendario'&&<Calendar/>} {page==='ideias'&&<Ideas/>} {page==='privacidade'&&<Privacy/>} {page==='instituicao'&&<Institution/>} {page==='ajuda'&&<Help go={go}/>}</main>
 <nav>{nav.map(([p,l,I])=><button key={p} className={page===p?'active':''} onClick={()=>go(p)}><I size={20}/><span>{l}</span></button>)}</nav>{modal&&<div/>}</div>
}
function HomePage({mood,setMood,tasks,habits,go}:{mood:string,setMood:(x:string)=>void,tasks:any[],habits:any[],go:(x:Page)=>void}){const hour=new Date().getHours();const greet=hour<12?'Bom dia!':hour<18?'Boa tarde!':'Boa noite!';return <div className="stack"><section className="hero"><div><span className="soft">{greet}</span><h2>Um passo de cada vez, Lucas.</h2><p>Cuidar de você também faz parte dos seus estudos.</p></div><div className="heroArt"><Heart size={34}/></div></section><section><div className="sectionTitle"><h3>Como você está hoje?</h3><button onClick={()=>go('checkin')}>Ver detalhes <ChevronRight size={16}/></button></div><div className="moods">{moods.map(([e,l])=><button className={mood===l?'selected':''} onClick={()=>setMood(l)} key={l}><span>{e}</span><small>{l}</small></button>)}</div></section><section className="quote"><div className="quoteIcon"><Sparkles size={19}/></div><div><span>Mensagem do dia</span><h3>{messages[new Date().getDate()%messages.length]}</h3></div><button onClick={()=>go('respirar')}>Começar <ChevronRight size={17}/></button></section><section className="feature"><div className="featureTop"><div className="tag">PARA VOCÊ</div><h2>Seu momento de hoje</h2><p>25 minutos de foco podem ajudar a dar um pequeno passo no que importa.</p></div><button className="primary" onClick={()=>go('pomodoro')}><Play size={17}/> Começar</button></section><section><div className="sectionTitle"><h3>Atalhos</h3></div><div className="quickGrid">{[['diario','Diário',Heart],['respirar','Respirar',Wind],['pomodoro','Pomodoro',Clock3],['tarefas','Tarefas',CheckCircle2],['habitos','Hábitos',Activity],['sons','Sons',CloudRain]].map(([p,l,I]:any)=><button onClick={()=>go(p)} key={p}><I size={21}/><span>{l}</span></button>)}</div></section><section className="dayCard"><div className="sectionTitle"><h3>Meu dia</h3><button onClick={()=>go('organizar')}>Ver tudo <ChevronRight size={16}/></button></div><div className="stats"><div><strong>{tasks.filter(t=>!t.done).length}</strong><span>tarefas pendentes</span></div><div><strong>{habits.filter(h=>h.done).length}/{habits.length}</strong><span>hábitos concluídos</span></div><div><strong>1h25</strong><span>de estudo</span></div></div></section><section className="continue"><h3>Continue de onde parou</h3><button onClick={()=>go('pomodoro')}><div><Clock3 size={21}/></div><span><strong>Pomodoro — 25 minutos</strong><small>Começar uma nova sessão</small></span><ChevronRight/></button><button onClick={()=>go('respirar')}><div><Wind size={21}/></div><span><strong>Respiração para pausa — 3 minutos</strong><small>Desacelerar por alguns minutos</small></span><ChevronRight/></button></section></div>}
function Cards({items,go}:{items:any[],go:(x:Page)=>void}){return <div className="cardGrid">{items.map(([p,l,d,I]:any)=><button className="bigCard" key={p} onClick={()=>go(p)}><div className="cardIcon"><I size={22}/></div><strong>{l}</strong><span>{d}</span><ChevronRight className="cardArrow" size={18}/></button>)}</div>}
function Organize({go,tasks,habits}:{go:(x:Page)=>void,tasks:any[],habits:any[]}){return <div className="stack"><p className="intro">Organize sua rotina sem transformar o dia em uma lista impossível.</p><Cards go={go} items={[["calendario","Calendário","Eventos e compromissos",CalendarDays],["tarefas","Tarefas",`${tasks.filter(t=>!t.done).length} pendentes`,ListTodo],["habitos","Hábitos",`${habits.filter(h=>h.done).length}/${habits.length} hoje`,Activity],["ideias","Caixa de ideias","Anote para depois",Lightbulb]]}/><Cards go={go} items={[["diario","Diário","Seu espaço pessoal",Heart],["checkin","Check-in","Registre seu momento",Brain],["instituicao","Instituição","Privacidade e vínculo",Target],["privacidade","Privacidade","Controle seus dados",Settings]]}/></div>}
function Study({go}:{go:(x:Page)=>void}){return <div className="stack"><section className="studyHero"><BookOpen size={28}/><div><h2>Pronto para focar?</h2><p>Seu progresso não precisa ser perfeito para ser real.</p></div></section><div className="studyStats"><div><strong>1h25</strong><span>estudado hoje</span></div><div><strong>2h</strong><span>meta diária</span></div><div><strong>3</strong><span>sessões hoje</span></div></div><Cards go={go} items={[["pomodoro","Pomodoro","25 min de foco",Clock3],["foco","Modo foco","Menos distrações",Target],["sons","Sons","Ambientes para focar",CloudRain],["respirar","Respirar","Pausa consciente",Wind],["progresso","Meu progresso","Veja sua evolução",Activity]]}/></div>}
function Well({go}:{go:(x:Page)=>void}){return <div className="stack"><section className="calm"><Heart size={30}/><h2>Seu bem-estar também importa.</h2><p>Encontre pequenos recursos para pausar, perceber como está e cuidar do seu ritmo.</p></section><Cards go={go} items={[["checkin","Check-in emocional","Como você está hoje?",Brain],["respirar","Respiração","Alguns minutos para desacelerar",Wind],["sons","Sons ambientes","Chuva, mar, floresta e mais",CloudRain],["diario","Diário","Escreva sem julgamentos",Heart],["ajuda","Preciso de ajuda","Recursos de apoio",CircleHelp]]}/></div>}
function Profile({go,dark,setDark}:{go:(x:Page)=>void,dark:boolean,setDark:(x:boolean)=>void}){return <div className="stack"><section className="profileCard"><div className="profileAvatar">L</div><div><h2>Lucas</h2><p>Análise e Desenvolvimento de Sistemas</p><small>lucas@exemplo.com</small></div></section><div className="settings">{[['Personalização','Escolha como o Equilibra aparece para você',Sparkles],['Notificações','Gerencie seus lembretes',Activity],['Privacidade','Seus dados e permissões',Settings],['Instituição','Vínculo e dados compartilhados',Target],['Preciso de ajuda','Recursos de acolhimento',CircleHelp]].map(([l,d,I]:any)=><button onClick={()=>go(l==='Privacidade'?'privacidade':l==='Instituição'?'instituicao':l==='Preciso de ajuda'?'ajuda':'perfil')} key={l}><I size={20}/><span><strong>{l}</strong><small>{d}</small></span><ChevronRight size={18}/></button>)}<div className="settingToggle"><Moon size={20}/><span><strong>Tema escuro</strong><small>Mais confortável à noite</small></span><button className={'toggle '+(dark?'on':'')} onClick={()=>setDark(!dark)}><i/></button></div></div><button className="danger">Sair da conta</button></div>}
function Checkin({mood,setMood}:{mood:string,setMood:(x:string)=>void}){const options=['Muito bem','Bem','Normal','Cansado','Ansioso','Estressado','Triste','Sobrecarregado'];return <div className="stack"><p className="intro">Registrar como você está pode ajudar a perceber seu momento. Isso não é um diagnóstico.</p><div className="optionGrid">{options.map(x=><button className={mood===x?'selected':''} onClick={()=>setMood(x)} key={x}>{x}</button>)}</div><h3>O que está influenciando seu dia?</h3><div className="chips">{['Estudos','Trabalho','Família','Relacionamentos','Sono','Falta de tempo','Dinheiro','Vida pessoal','Não sei','Outro'].map(x=><button key={x}>{x}</button>)}</div><textarea placeholder="Quer contar mais alguma coisa? (opcional)"/><button className="primary">Salvar check-in <Check size={17}/></button><div className="notice">Obrigado por registrar como você está. Você pode voltar a isso quando quiser.</div></div>}
function Tasks({tasks,setTasks}:{tasks:any[],setTasks:Function}){const [name,setName]=useState('');return <div className="stack"><div className="progressLine"><span>4 de 7 tarefas concluídas</span><div><i style={{width:'57%'}}/></div></div><div className="addRow"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nova tarefa..."/><button onClick={()=>{if(name.trim()){setTasks([...tasks,{id:Date.now(),name,time:'Hoje',priority:'Média',done:false}]);setName('')}}}><Plus/></button></div><div className="taskList">{tasks.map(t=><div className={'task '+(t.done?'done':'')} key={t.id}><button className="check" onClick={()=>setTasks(tasks.map((x:any)=>x.id===t.id?{...x,done:!x.done}:x))}>{t.done&&<Check size={15}/>}</button><span><strong>{t.name}</strong><small>{t.time} · prioridade {t.priority.toLowerCase()}</small></span><button className="delete" onClick={()=>setTasks(tasks.filter((x:any)=>x.id!==t.id))}><X size={17}/></button></div>)}</div></div>}
function Habits({habits,setHabits}:{habits:any[],setHabits:Function}){return <div className="stack"><p className="intro">Consistência é construída aos poucos. Se hoje não der, tudo bem tentar novamente amanhã.</p><div className="habitList">{habits.map(h=><div className={'habit '+(h.done?'done':'')} key={h.id}><span className="habitEmoji">{h.icon}</span><span><strong>{h.name}</strong><small>Seg · Ter · Qua · Qui · Sex</small></span><button className={'toggle '+(h.done?'on':'')} onClick={()=>setHabits(habits.map((x:any)=>x.id===h.id?{...x,done:!x.done}:x))}><i/></button></div>)}</div><button className="outline"><Plus size={17}/> Criar hábito</button></div>}
function Pomodoro(){const [sec,setSec]=useState(1500);const [run,setRun]=useState(false);useEffect(()=>{if(!run)return;const id=setInterval(()=>setSec(s=>s>0?s-1:1500),1000);return()=>clearInterval(id)},[run]);return <div className="timerPage"><div className="timerRing"><span>{String(Math.floor(sec/60)).padStart(2,'0')}:{String(sec%60).padStart(2,'0')}</span><small>{run?'Foco em andamento':'Pronto para começar'}</small></div><div className="timerActions"><button className="primary" onClick={()=>setRun(!run)}>{run?'Pausar':'Iniciar'} <Play size={17}/></button><button className="outline" onClick={()=>{setRun(false);setSec(1500)}}>Reiniciar</button></div><div className="timerStats"><strong>3</strong><span>sessões concluídas hoje</span></div><p className="notice">25 minutos de foco · 5 minutos de pausa</p></div>}
function Focus(){return <div className="focusPage"><Target size={35}/><span>VOCÊ ESTÁ NO</span><h2>Modo foco.</h2><div className="focusTimer">25:00</div><p>Estudar Banco de Dados</p><button className="primary"><Play size={17}/> Iniciar foco</button></div>}
function Sounds(){return <div className="stack"><p className="intro">Escolha um ambiente para acompanhar seus estudos ou momentos de pausa.</p><div className="soundGrid">{[['Chuva',CloudRain],['Floresta',Sun],['Mar',Wind],['Café',Activity],['Ruído branco',Activity],['Ventilador',Wind],['Noite',Moon],['Instrumental',BookOpen]].map(([n,I]:any)=><button key={n}><div><I size={22}/></div><span>{n}</span><Play size={17}/></button>)}</div><div className="player"><CloudRain size={21}/><span><strong>Chuva</strong><small>Reproduzindo</small></span><input type="range" defaultValue="60"/><button><X size={18}/></button></div></div>}
function Breathing(){const [active,setActive]=useState(false);return <div className="breath"><div className={'breathCircle '+(active?'active':'')}><span>{active?'Inspire':'Respire'}</span></div><h2>Respire</h2><p>Reserve alguns minutos para desacelerar e acompanhar sua respiração.</p><div className="breathOptions"><button onClick={()=>setActive(!active)}>Respiração calma <small>2 min</small></button><button onClick={()=>setActive(!active)}>Respiração profunda <small>5 min</small></button><button onClick={()=>setActive(!active)}>Antes de estudar <small>2 min</small></button></div></div>}
function Progress(){return <div className="stack"><div className="metricGrid"><div><strong>7h35</strong><span>estudadas esta semana</span></div><div><strong>18</strong><span>tarefas concluídas</span></div><div><strong>12</strong><span>sessões de foco</span></div></div><div className="chart"><h3>Horas estudadas</h3><div className="bars">{[1.3,2.1,.75,1.6,2,0.8,1.1].map((v,i)=><div key={i}><i style={{height:`${v/2.1*100}%`}}/><small>{['S','T','Q','Q','S','S','D'][i]}</small></div>)}</div></div><div className="positive">✨ Você está construindo seu ritmo. Continue no seu tempo.</div></div>}
function Calendar(){return <div className="stack"><div className="calendarHead"><button>‹</button><strong>Agosto 2026</strong><button>›</button></div><div className="calendar"><div className="week">{['D','S','T','Q','Q','S','S'].map(x=><span key={x}>{x}</span>)}</div><div className="days">{Array.from({length:31},(_,i)=><button className={i+1===29?'today':''} key={i}>{i+1}</button>)}</div></div><button className="primary"><Plus size={17}/> Criar evento</button></div>}
function Journal({journal,setJournal}:{journal:any[],setJournal:Function}){const [text,setText]=useState('');return <div className="stack"><div className="privacyLine">🔒 Seus registros pessoais são privados.</div><div className="journalNew"><input placeholder="Título da entrada"/><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Escreva o que estiver passando pela sua cabeça..."/><button className="primary" onClick={()=>{if(text.trim()){setJournal([{id:Date.now(),date:new Date().toLocaleDateString('pt-BR'),text},...journal]);setText('')}}}>Salvar entrada</button></div>{journal.length===0?<div className="empty"><Heart size={25}/><h3>Seu espaço está esperando por você.</h3><p>Escreva sua primeira entrada quando sentir vontade.</p></div>:journal.map(j=><article className="entry" key={j.id}><small>{j.date}</small><p>{j.text}</p></article>)}</div>}
function Ideas(){const [items,setItems]=useState(['Revisar projeto do TCC','Pesquisar referências de UX']);const [v,setV]=useState('');return <div className="stack"><div className="addRow"><input value={v} onChange={e=>setV(e.target.value)} placeholder="Anote uma ideia..."/><button onClick={()=>{if(v.trim()){setItems([v,...items]);setV('')}}}><Plus/></button></div><div className="chips"><button>Todas</button><button>Pendentes</button><button>Concluídas</button></div>{items.map((x,i)=><div className="idea" key={x}><Lightbulb size={19}/><span><strong>{x}</strong><small>Ideia · agora</small></span><button onClick={()=>setItems(items.filter((_,n)=>n!==i))}><Check size={18}/></button></div>)}</div>}
function Privacy(){return <div className="stack"><div className="privacyHero"><Settings size={28}/><h2>Você decide sobre seus dados.</h2><p>O Equilibra foi pensado para manter seu espaço pessoal separado de informações institucionais.</p></div>{[['Seus dados pessoais','Nome, e-mail e preferências'],['Dados do diário','Seu diário é pessoal e privado.'],['Dados de uso','Usados para melhorar sua experiência.'],['Instituição','Quando aplicável, dados são apresentados de forma agregada.']].map(([a,b])=><div className="privacyItem" key={a}><CheckCircle2 size={20}/><span><strong>{a}</strong><small>{b}</small></span></div>)}<button className="outline">Exportar meus dados</button><button className="danger">Excluir minha conta</button></div>}
function Institution(){return <div className="stack"><div className="institutionHero"><Target size={27}/><h2>Visão geral dos estudantes</h2><p>Dados exclusivamente simulados e agregados para demonstração acadêmica.</p></div><div className="metricGrid"><div><strong>248</strong><span>estudantes associados</span></div><div><strong>176</strong><span>usuários ativos</span></div><div><strong>71%</strong><span>participação semanal</span></div></div><div className="chart"><h3>Uso das ferramentas</h3><div className="usage">{[['Respiração',68],['Estudos',82],['Hábitos',54],['Sons',43]].map(([x,v]:any)=><div key={x}><span>{x}</span><div><i style={{width:v+'%'}}/></div><b>{v}%</b></div>)}</div></div><div className="notice">Exemplo: 32% dos usuários utilizaram exercícios de respiração esta semana. Nenhum dado individual é exibido.</div></div>}
function Help({go}:{go:(x:Page)=>void}){return <div className="stack"><div className="helpHero"><Heart size={30}/><h2>Você não precisa lidar com tudo sozinho.</h2><p>Escolha um recurso para este momento.</p></div><button className="helpItem" onClick={()=>go('respirar')}><Wind/><span><strong>Quero desacelerar</strong><small>Ir para respiração</small></span><ChevronRight/></button><button className="helpItem" onClick={()=>go('respirar')}><Heart/><span><strong>Estou me sentindo sobrecarregado</strong><small>Pausa e recursos disponíveis</small></span><ChevronRight/></button><div className="notice"><strong>Precisa de apoio profissional?</strong><br/>O Equilibra não substitui psicólogo, psiquiatra, médico ou atendimento profissional. Em uma situação de risco imediato, procure um serviço de emergência apropriado.</div></div>}
function AppExtra(){return null}
createRoot(document.getElementById('root')!).render(<App/>);
